# Generated by Django 6.0.4 on 2026-05-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='Student Name')),
                ('age', models.ImageField(blank=True, null=True, upload_to='')),
                ('fName', models.CharField(max_length=50)),
            ],
        ),
    ]
