# Generated by Django 6.0.4 on 2026-05-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
